services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rigops
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  core-api:
    build: ./backend/RigOps.Api
    ports:
      - "5275:8080"
    environment:
      ConnectionStrings__RigOpsDb: "Host=postgres;Database=rigops;Username=postgres;Password=postgres"
      TelemetryServiceUrl: "http://telemetry-service:3001"
      AiServiceUrl: "http://ai-service:8000"
      NotificationServiceUrl: "http://notification-service:3002"
    depends_on:
      postgres:
        condition: service_healthy

  telemetry-service:
    build: ./telemetry-service
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/rigops"
      PORT: 3001
    depends_on:
      postgres:
        condition: service_healthy

  notification-service:
    build: ./notification-service
    ports:
      - "3002:3002"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/rigops"
      PORT: 3002
    depends_on:
      postgres:
        condition: service_healthy

  ai-service:
    build: ./ai-service
    ports:
      - "8000:8000"

volumes:
  pgdata: